// app/layout.tsx
import "./globals.css";
import "./animations.css";
import Header from "./components/Header";
import NotificationBar from "./components/NotificationBar";
import UniversityFooter from "./components/Footer";
import { Providers } from "./providers"; // Import the provider
import SocialMediaGlobe from './components/SocialMediaIcons';
import AccessibilityButton from "./components/AccessibilityButton"
import BrandColorSelector from "./components/BrandColorSelector"
import { LanguageProvider } from "@/context/LanguageContext";
import { SearchProvider } from "@/context/SearchContext";
import HtmlLang from "./HtmlLang";


export const metadata = {
  title: "University Website",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased">
     
        {/* Use the Providers wrapper */}
        <Providers>
        <LanguageProvider>
        <HtmlLang /> 
        <SearchProvider>
          {/* FIXED TOP WRAPPER */}
<div className="fixed top-0 left-0 w-full z-[2000] bg-white shadow-sm">
  <Header />
  <NotificationBar />
</div>


          {/* PAGE CONTENT OFFSET BELOW HEADER + BAR */}
          <main className="pt-[var(--top-offset)] min-h-screen">

            {children}
            <SocialMediaGlobe />
            <AccessibilityButton />
          </main>
          <BrandColorSelector />
          {/* FOOTER */}
          <UniversityFooter />
          </SearchProvider>
          </LanguageProvider>
        </Providers>
        
      </body>
    </html>
  );
}