// app/layout.tsx
import "./globals.css";
import "./animations.css";
import Header from "./components/Header";
import NotificationBar from "./components/NotificationBar";
import UniversityFooter from "./components/Footer";
import { Providers } from "./providers"; // Import the provider
import SocialMediaGlobe from './components/SocialMediaIcons';
import AccessibilityButton from "./components/AccessibilityButton"
import { LanguageProvider } from "@/context/LanguageContext";
import { SearchProvider } from "@/context/SearchContext";
import HtmlLang from "./HtmlLang";


export const metadata = {
  title: "University Website",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased">
     
        {/* Use the Providers wrapper */}
        <Providers>
        <LanguageProvider>
        <HtmlLang /> 
        <SearchProvider>
          {/* FIXED HEADER */}
          <header className="fixed top-0 left-0 w-full bg-white z-[2000] shadow-sm">
            <Header />
          </header>

          {/* FIXED NOTIFICATION BAR UNDER HEADER */}
          <div className="fixed top-[128px] md:top-24 left-0 w-full z-[1500]">
            <NotificationBar />
          </div>

          {/* PAGE CONTENT OFFSET BELOW HEADER + BAR */}
          <main className="pt-[160px] md:pt-[104px] min-h-screen">

            {children}
            <SocialMediaGlobe />
            <AccessibilityButton />
          </main>

          {/* FOOTER */}
          <UniversityFooter />
          </SearchProvider>
          </LanguageProvider>
        </Providers>
        
      </body>
    </html>
  );
}